//AUTO-GENERATED File, caution before modifying

#ifndef vulkan_structs_meta_hpp
 #define vulkan_structs_meta_hpp

#include "visit_struct.hpp"


VISITABLE_STRUCT(VkApplicationInfo,sType,pNext,pApplicationName,applicationVersion,pEngineName,engineVersion,apiVersion);

VISITABLE_STRUCT(VkInstanceCreateInfo,sType,pNext,flags,pApplicationInfo,enabledLayerCount,ppEnabledLayerNames,enabledExtensionCount,ppEnabledExtensionNames);

VISITABLE_STRUCT(VkAllocationCallbacks,pUserData,pfnAllocation,pfnReallocation,pfnFree,pfnInternalAllocation,pfnInternalFree);

VISITABLE_STRUCT(VkPhysicalDeviceFeatures,robustBufferAccess,fullDrawIndexUint32,imageCubeArray,independentBlend,geometryShader,tessellationShader,sampleRateShading,dualSrcBlend,logicOp,multiDrawIndirect,drawIndirectFirstInstance,depthClamp,depthBiasClamp,fillModeNonSolid,depthBounds,wideLines,largePoints,alphaToOne,multiViewport,samplerAnisotropy,textureCompressionETC2,textureCompressionASTC_LDR,textureCompressionBC,occlusionQueryPrecise,pipelineStatisticsQuery,vertexPipelineStoresAndAtomics,fragmentStoresAndAtomics,shaderTessellationAndGeometryPointSize,shaderImageGatherExtended,shaderStorageImageExtendedFormats,shaderStorageImageMultisample,shaderStorageImageReadWithoutFormat,shaderStorageImageWriteWithoutFormat,shaderUniformBufferArrayDynamicIndexing,shaderSampledImageArrayDynamicIndexing,shaderStorageBufferArrayDynamicIndexing,shaderStorageImageArrayDynamicIndexing,shaderClipDistance,shaderCullDistance,shaderFloat64,shaderInt64,shaderInt16,shaderResourceResidency,shaderResourceMinLod,sparseBinding,sparseResidencyBuffer,sparseResidencyImage2D,sparseResidencyImage3D,sparseResidency2Samples,sparseResidency4Samples,sparseResidency8Samples,sparseResidency16Samples,sparseResidencyAliased,variableMultisampleRate,inheritedQueries);

VISITABLE_STRUCT(VkFormatProperties,linearTilingFeatures,optimalTilingFeatures,bufferFeatures);

VISITABLE_STRUCT(VkExtent3D,width,height,depth);

VISITABLE_STRUCT(VkImageFormatProperties,maxExtent,maxMipLevels,maxArrayLayers,sampleCounts,maxResourceSize);

VISITABLE_STRUCT(VkPhysicalDeviceLimits,maxImageDimension1D,maxImageDimension2D,maxImageDimension3D,maxImageDimensionCube,maxImageArrayLayers,maxTexelBufferElements,maxUniformBufferRange,maxStorageBufferRange,maxPushConstantsSize,maxMemoryAllocationCount,maxSamplerAllocationCount,bufferImageGranularity,sparseAddressSpaceSize,maxBoundDescriptorSets,maxPerStageDescriptorSamplers,maxPerStageDescriptorUniformBuffers,maxPerStageDescriptorStorageBuffers,maxPerStageDescriptorSampledImages,maxPerStageDescriptorStorageImages,maxPerStageDescriptorInputAttachments,maxPerStageResources,maxDescriptorSetSamplers,maxDescriptorSetUniformBuffers,maxDescriptorSetUniformBuffersDynamic,maxDescriptorSetStorageBuffers,maxDescriptorSetStorageBuffersDynamic,maxDescriptorSetSampledImages,maxDescriptorSetStorageImages,maxDescriptorSetInputAttachments,maxVertexInputAttributes,maxVertexInputBindings,maxVertexInputAttributeOffset,maxVertexInputBindingStride,maxVertexOutputComponents,maxTessellationGenerationLevel,maxTessellationPatchSize,maxTessellationControlPerVertexInputComponents,maxTessellationControlPerVertexOutputComponents,maxTessellationControlPerPatchOutputComponents,maxTessellationControlTotalOutputComponents,maxTessellationEvaluationInputComponents,maxTessellationEvaluationOutputComponents,maxGeometryShaderInvocations,maxGeometryInputComponents,maxGeometryOutputComponents,maxGeometryOutputVertices,maxGeometryTotalOutputComponents,maxFragmentInputComponents,maxFragmentOutputAttachments,maxFragmentDualSrcAttachments,maxFragmentCombinedOutputResources,maxComputeSharedMemorySize,maxComputeWorkGroupCount,maxComputeWorkGroupInvocations,maxComputeWorkGroupSize,subPixelPrecisionBits,subTexelPrecisionBits,mipmapPrecisionBits,maxDrawIndexedIndexValue,maxDrawIndirectCount,maxSamplerLodBias,maxSamplerAnisotropy,maxViewports,maxViewportDimensions,viewportBoundsRange,viewportSubPixelBits,minMemoryMapAlignment,minTexelBufferOffsetAlignment,minUniformBufferOffsetAlignment,minStorageBufferOffsetAlignment,minTexelOffset,maxTexelOffset,minTexelGatherOffset,maxTexelGatherOffset,minInterpolationOffset,maxInterpolationOffset,subPixelInterpolationOffsetBits,maxFramebufferWidth,maxFramebufferHeight,maxFramebufferLayers,framebufferColorSampleCounts,framebufferDepthSampleCounts,framebufferStencilSampleCounts,framebufferNoAttachmentsSampleCounts,maxColorAttachments,sampledImageColorSampleCounts,sampledImageIntegerSampleCounts,sampledImageDepthSampleCounts,sampledImageStencilSampleCounts,storageImageSampleCounts,maxSampleMaskWords,timestampComputeAndGraphics,timestampPeriod,maxClipDistances,maxCullDistances,maxCombinedClipAndCullDistances,discreteQueuePriorities,pointSizeRange,lineWidthRange,pointSizeGranularity,lineWidthGranularity,strictLines,standardSampleLocations,optimalBufferCopyOffsetAlignment,optimalBufferCopyRowPitchAlignment,nonCoherentAtomSize);

VISITABLE_STRUCT(VkPhysicalDeviceSparseProperties,residencyStandard2DBlockShape,residencyStandard2DMultisampleBlockShape,residencyStandard3DBlockShape,residencyAlignedMipSize,residencyNonResidentStrict);

VISITABLE_STRUCT(VkPhysicalDeviceProperties,apiVersion,driverVersion,vendorID,deviceID,deviceType,deviceName,pipelineCacheUUID,limits,sparseProperties);

VISITABLE_STRUCT(VkQueueFamilyProperties,queueFlags,queueCount,timestampValidBits,minImageTransferGranularity);

VISITABLE_STRUCT(VkMemoryType,propertyFlags,heapIndex);

VISITABLE_STRUCT(VkMemoryHeap,size,flags);

VISITABLE_STRUCT(VkPhysicalDeviceMemoryProperties,memoryTypeCount,memoryTypes,memoryHeapCount,memoryHeaps);

VISITABLE_STRUCT(VkDeviceQueueCreateInfo,sType,pNext,flags,queueFamilyIndex,queueCount,pQueuePriorities);

VISITABLE_STRUCT(VkDeviceCreateInfo,sType,pNext,flags,queueCreateInfoCount,pQueueCreateInfos,enabledLayerCount,ppEnabledLayerNames,enabledExtensionCount,ppEnabledExtensionNames,pEnabledFeatures);

VISITABLE_STRUCT(VkExtensionProperties,extensionName,specVersion);

VISITABLE_STRUCT(VkLayerProperties,layerName,specVersion,implementationVersion,description);

VISITABLE_STRUCT(VkSubmitInfo,sType,pNext,waitSemaphoreCount,pWaitSemaphores,pWaitDstStageMask,commandBufferCount,pCommandBuffers,signalSemaphoreCount,pSignalSemaphores);

VISITABLE_STRUCT(VkMemoryAllocateInfo,sType,pNext,allocationSize,memoryTypeIndex);

VISITABLE_STRUCT(VkMappedMemoryRange,sType,pNext,memory,offset,size);

VISITABLE_STRUCT(VkMemoryRequirements,size,alignment,memoryTypeBits);

VISITABLE_STRUCT(VkSparseImageFormatProperties,aspectMask,imageGranularity,flags);

VISITABLE_STRUCT(VkSparseImageMemoryRequirements,formatProperties,imageMipTailFirstLod,imageMipTailSize,imageMipTailOffset,imageMipTailStride);

VISITABLE_STRUCT(VkSparseMemoryBind,resourceOffset,size,memory,memoryOffset,flags);

VISITABLE_STRUCT(VkSparseBufferMemoryBindInfo,buffer,bindCount,pBinds);

VISITABLE_STRUCT(VkSparseImageOpaqueMemoryBindInfo,image,bindCount,pBinds);

VISITABLE_STRUCT(VkImageSubresource,aspectMask,mipLevel,arrayLayer);

VISITABLE_STRUCT(VkOffset3D,x,y,z);

VISITABLE_STRUCT(VkSparseImageMemoryBind,subresource,offset,extent,memory,memoryOffset,flags);

VISITABLE_STRUCT(VkSparseImageMemoryBindInfo,image,bindCount,pBinds);

VISITABLE_STRUCT(VkBindSparseInfo,sType,pNext,waitSemaphoreCount,pWaitSemaphores,bufferBindCount,pBufferBinds,imageOpaqueBindCount,pImageOpaqueBinds,imageBindCount,pImageBinds,signalSemaphoreCount,pSignalSemaphores);

VISITABLE_STRUCT(VkFenceCreateInfo,sType,pNext,flags);

VISITABLE_STRUCT(VkSemaphoreCreateInfo,sType,pNext,flags);

VISITABLE_STRUCT(VkEventCreateInfo,sType,pNext,flags);

VISITABLE_STRUCT(VkQueryPoolCreateInfo,sType,pNext,flags,queryType,queryCount,pipelineStatistics);

VISITABLE_STRUCT(VkBufferCreateInfo,sType,pNext,flags,size,usage,sharingMode,queueFamilyIndexCount,pQueueFamilyIndices);

VISITABLE_STRUCT(VkBufferViewCreateInfo,sType,pNext,flags,buffer,format,offset,range);

VISITABLE_STRUCT(VkImageCreateInfo,sType,pNext,flags,imageType,format,extent,mipLevels,arrayLayers,samples,tiling,usage,sharingMode,queueFamilyIndexCount,pQueueFamilyIndices,initialLayout);

VISITABLE_STRUCT(VkSubresourceLayout,offset,size,rowPitch,arrayPitch,depthPitch);

VISITABLE_STRUCT(VkComponentMapping,r,g,b,a);

VISITABLE_STRUCT(VkImageSubresourceRange,aspectMask,baseMipLevel,levelCount,baseArrayLayer,layerCount);

VISITABLE_STRUCT(VkImageViewCreateInfo,sType,pNext,flags,image,viewType,format,components,subresourceRange);

VISITABLE_STRUCT(VkShaderModuleCreateInfo,sType,pNext,flags,codeSize,pCode);

VISITABLE_STRUCT(VkPipelineCacheCreateInfo,sType,pNext,flags,initialDataSize,pInitialData);

VISITABLE_STRUCT(VkSpecializationMapEntry,constantID,offset,size);

VISITABLE_STRUCT(VkSpecializationInfo,mapEntryCount,pMapEntries,dataSize,pData);

VISITABLE_STRUCT(VkPipelineShaderStageCreateInfo,sType,pNext,flags,stage,module,pName,pSpecializationInfo);

VISITABLE_STRUCT(VkVertexInputBindingDescription,binding,stride,inputRate);

VISITABLE_STRUCT(VkVertexInputAttributeDescription,location,binding,format,offset);

VISITABLE_STRUCT(VkPipelineVertexInputStateCreateInfo,sType,pNext,flags,vertexBindingDescriptionCount,pVertexBindingDescriptions,vertexAttributeDescriptionCount,pVertexAttributeDescriptions);

VISITABLE_STRUCT(VkPipelineInputAssemblyStateCreateInfo,sType,pNext,flags,topology,primitiveRestartEnable);

VISITABLE_STRUCT(VkPipelineTessellationStateCreateInfo,sType,pNext,flags,patchControlPoints);

VISITABLE_STRUCT(VkViewport,x,y,width,height,minDepth,maxDepth);

VISITABLE_STRUCT(VkOffset2D,x,y);

VISITABLE_STRUCT(VkExtent2D,width,height);

VISITABLE_STRUCT(VkRect2D,offset,extent);

VISITABLE_STRUCT(VkPipelineViewportStateCreateInfo,sType,pNext,flags,viewportCount,pViewports,scissorCount,pScissors);

VISITABLE_STRUCT(VkPipelineRasterizationStateCreateInfo,sType,pNext,flags,depthClampEnable,rasterizerDiscardEnable,polygonMode,cullMode,frontFace,depthBiasEnable,depthBiasConstantFactor,depthBiasClamp,depthBiasSlopeFactor,lineWidth);

VISITABLE_STRUCT(VkPipelineMultisampleStateCreateInfo,sType,pNext,flags,rasterizationSamples,sampleShadingEnable,minSampleShading,pSampleMask,alphaToCoverageEnable,alphaToOneEnable);

VISITABLE_STRUCT(VkStencilOpState,failOp,passOp,depthFailOp,compareOp,compareMask,writeMask,reference);

VISITABLE_STRUCT(VkPipelineDepthStencilStateCreateInfo,sType,pNext,flags,depthTestEnable,depthWriteEnable,depthCompareOp,depthBoundsTestEnable,stencilTestEnable,front,back,minDepthBounds,maxDepthBounds);

VISITABLE_STRUCT(VkPipelineColorBlendAttachmentState,blendEnable,srcColorBlendFactor,dstColorBlendFactor,colorBlendOp,srcAlphaBlendFactor,dstAlphaBlendFactor,alphaBlendOp,colorWriteMask);

VISITABLE_STRUCT(VkPipelineColorBlendStateCreateInfo,sType,pNext,flags,logicOpEnable,logicOp,attachmentCount,pAttachments,blendConstants);

VISITABLE_STRUCT(VkPipelineDynamicStateCreateInfo,sType,pNext,flags,dynamicStateCount,pDynamicStates);

VISITABLE_STRUCT(VkGraphicsPipelineCreateInfo,sType,pNext,flags,stageCount,pStages,pVertexInputState,pInputAssemblyState,pTessellationState,pViewportState,pRasterizationState,pMultisampleState,pDepthStencilState,pColorBlendState,pDynamicState,layout,renderPass,subpass,basePipelineHandle,basePipelineIndex);

VISITABLE_STRUCT(VkComputePipelineCreateInfo,sType,pNext,flags,stage,layout,basePipelineHandle,basePipelineIndex);

VISITABLE_STRUCT(VkPushConstantRange,stageFlags,offset,size);

VISITABLE_STRUCT(VkPipelineLayoutCreateInfo,sType,pNext,flags,setLayoutCount,pSetLayouts,pushConstantRangeCount,pPushConstantRanges);

VISITABLE_STRUCT(VkSamplerCreateInfo,sType,pNext,flags,magFilter,minFilter,mipmapMode,addressModeU,addressModeV,addressModeW,mipLodBias,anisotropyEnable,maxAnisotropy,compareEnable,compareOp,minLod,maxLod,borderColor,unnormalizedCoordinates);

VISITABLE_STRUCT(VkDescriptorSetLayoutBinding,binding,descriptorType,descriptorCount,stageFlags,pImmutableSamplers);

VISITABLE_STRUCT(VkDescriptorSetLayoutCreateInfo,sType,pNext,flags,bindingCount,pBindings);

VISITABLE_STRUCT(VkDescriptorPoolSize,type,descriptorCount);

VISITABLE_STRUCT(VkDescriptorPoolCreateInfo,sType,pNext,flags,maxSets,poolSizeCount,pPoolSizes);

VISITABLE_STRUCT(VkDescriptorSetAllocateInfo,sType,pNext,descriptorPool,descriptorSetCount,pSetLayouts);

VISITABLE_STRUCT(VkDescriptorImageInfo,sampler,imageView,imageLayout);

VISITABLE_STRUCT(VkDescriptorBufferInfo,buffer,offset,range);

VISITABLE_STRUCT(VkWriteDescriptorSet,sType,pNext,dstSet,dstBinding,dstArrayElement,descriptorCount,descriptorType,pImageInfo,pBufferInfo,pTexelBufferView);

VISITABLE_STRUCT(VkCopyDescriptorSet,sType,pNext,srcSet,srcBinding,srcArrayElement,dstSet,dstBinding,dstArrayElement,descriptorCount);

VISITABLE_STRUCT(VkFramebufferCreateInfo,sType,pNext,flags,renderPass,attachmentCount,pAttachments,width,height,layers);

VISITABLE_STRUCT(VkAttachmentDescription,flags,format,samples,loadOp,storeOp,stencilLoadOp,stencilStoreOp,initialLayout,finalLayout);

VISITABLE_STRUCT(VkAttachmentReference,attachment,layout);

VISITABLE_STRUCT(VkSubpassDescription,flags,pipelineBindPoint,inputAttachmentCount,pInputAttachments,colorAttachmentCount,pColorAttachments,pResolveAttachments,pDepthStencilAttachment,preserveAttachmentCount,pPreserveAttachments);

VISITABLE_STRUCT(VkSubpassDependency,srcSubpass,dstSubpass,srcStageMask,dstStageMask,srcAccessMask,dstAccessMask,dependencyFlags);

VISITABLE_STRUCT(VkRenderPassCreateInfo,sType,pNext,flags,attachmentCount,pAttachments,subpassCount,pSubpasses,dependencyCount,pDependencies);

VISITABLE_STRUCT(VkCommandPoolCreateInfo,sType,pNext,flags,queueFamilyIndex);

VISITABLE_STRUCT(VkCommandBufferAllocateInfo,sType,pNext,commandPool,level,commandBufferCount);

VISITABLE_STRUCT(VkCommandBufferInheritanceInfo,sType,pNext,renderPass,subpass,framebuffer,occlusionQueryEnable,queryFlags,pipelineStatistics);

VISITABLE_STRUCT(VkCommandBufferBeginInfo,sType,pNext,flags,pInheritanceInfo);

VISITABLE_STRUCT(VkBufferCopy,srcOffset,dstOffset,size);

VISITABLE_STRUCT(VkImageSubresourceLayers,aspectMask,mipLevel,baseArrayLayer,layerCount);

VISITABLE_STRUCT(VkImageCopy,srcSubresource,srcOffset,dstSubresource,dstOffset,extent);

VISITABLE_STRUCT(VkImageBlit,srcSubresource,srcOffsets,dstSubresource,dstOffsets);

VISITABLE_STRUCT(VkBufferImageCopy,bufferOffset,bufferRowLength,bufferImageHeight,imageSubresource,imageOffset,imageExtent);

VISITABLE_STRUCT(VkClearDepthStencilValue,depth,stencil);

VISITABLE_STRUCT(VkClearAttachment,aspectMask,colorAttachment,clearValue);

VISITABLE_STRUCT(VkClearRect,rect,baseArrayLayer,layerCount);

VISITABLE_STRUCT(VkImageResolve,srcSubresource,srcOffset,dstSubresource,dstOffset,extent);

VISITABLE_STRUCT(VkMemoryBarrier,sType,pNext,srcAccessMask,dstAccessMask);

VISITABLE_STRUCT(VkBufferMemoryBarrier,sType,pNext,srcAccessMask,dstAccessMask,srcQueueFamilyIndex,dstQueueFamilyIndex,buffer,offset,size);

VISITABLE_STRUCT(VkImageMemoryBarrier,sType,pNext,srcAccessMask,dstAccessMask,oldLayout,newLayout,srcQueueFamilyIndex,dstQueueFamilyIndex,image,subresourceRange);

VISITABLE_STRUCT(VkRenderPassBeginInfo,sType,pNext,renderPass,framebuffer,renderArea,clearValueCount,pClearValues);

VISITABLE_STRUCT(VkDispatchIndirectCommand,x,y,z);

VISITABLE_STRUCT(VkDrawIndexedIndirectCommand,indexCount,instanceCount,firstIndex,vertexOffset,firstInstance);

VISITABLE_STRUCT(VkDrawIndirectCommand,vertexCount,instanceCount,firstVertex,firstInstance);

VISITABLE_STRUCT(VkBaseOutStructure,sType,pNext);

VISITABLE_STRUCT(VkBaseInStructure,sType,pNext);

VISITABLE_STRUCT(VkPhysicalDeviceSubgroupProperties,sType,pNext,subgroupSize,supportedStages,supportedOperations,quadOperationsInAllStages);

VISITABLE_STRUCT(VkBindBufferMemoryInfo,sType,pNext,buffer,memory,memoryOffset);

VISITABLE_STRUCT(VkBindImageMemoryInfo,sType,pNext,image,memory,memoryOffset);

VISITABLE_STRUCT(VkPhysicalDevice16BitStorageFeatures,sType,pNext,storageBuffer16BitAccess,uniformAndStorageBuffer16BitAccess,storagePushConstant16,storageInputOutput16);

VISITABLE_STRUCT(VkMemoryDedicatedRequirements,sType,pNext,prefersDedicatedAllocation,requiresDedicatedAllocation);

VISITABLE_STRUCT(VkMemoryDedicatedAllocateInfo,sType,pNext,image,buffer);

VISITABLE_STRUCT(VkMemoryAllocateFlagsInfo,sType,pNext,flags,deviceMask);

VISITABLE_STRUCT(VkDeviceGroupRenderPassBeginInfo,sType,pNext,deviceMask,deviceRenderAreaCount,pDeviceRenderAreas);

VISITABLE_STRUCT(VkDeviceGroupCommandBufferBeginInfo,sType,pNext,deviceMask);

VISITABLE_STRUCT(VkDeviceGroupSubmitInfo,sType,pNext,waitSemaphoreCount,pWaitSemaphoreDeviceIndices,commandBufferCount,pCommandBufferDeviceMasks,signalSemaphoreCount,pSignalSemaphoreDeviceIndices);

VISITABLE_STRUCT(VkDeviceGroupBindSparseInfo,sType,pNext,resourceDeviceIndex,memoryDeviceIndex);

VISITABLE_STRUCT(VkBindBufferMemoryDeviceGroupInfo,sType,pNext,deviceIndexCount,pDeviceIndices);

VISITABLE_STRUCT(VkBindImageMemoryDeviceGroupInfo,sType,pNext,deviceIndexCount,pDeviceIndices,splitInstanceBindRegionCount,pSplitInstanceBindRegions);

VISITABLE_STRUCT(VkPhysicalDeviceGroupProperties,sType,pNext,physicalDeviceCount,physicalDevices,subsetAllocation);

VISITABLE_STRUCT(VkDeviceGroupDeviceCreateInfo,sType,pNext,physicalDeviceCount,pPhysicalDevices);

VISITABLE_STRUCT(VkBufferMemoryRequirementsInfo2,sType,pNext,buffer);

VISITABLE_STRUCT(VkImageMemoryRequirementsInfo2,sType,pNext,image);

VISITABLE_STRUCT(VkImageSparseMemoryRequirementsInfo2,sType,pNext,image);

VISITABLE_STRUCT(VkMemoryRequirements2,sType,pNext,memoryRequirements);

VISITABLE_STRUCT(VkSparseImageMemoryRequirements2,sType,pNext,memoryRequirements);

VISITABLE_STRUCT(VkPhysicalDeviceFeatures2,sType,pNext,features);

VISITABLE_STRUCT(VkPhysicalDeviceProperties2,sType,pNext,properties);

VISITABLE_STRUCT(VkFormatProperties2,sType,pNext,formatProperties);

VISITABLE_STRUCT(VkImageFormatProperties2,sType,pNext,imageFormatProperties);

VISITABLE_STRUCT(VkPhysicalDeviceImageFormatInfo2,sType,pNext,format,type,tiling,usage,flags);

VISITABLE_STRUCT(VkQueueFamilyProperties2,sType,pNext,queueFamilyProperties);

VISITABLE_STRUCT(VkPhysicalDeviceMemoryProperties2,sType,pNext,memoryProperties);

VISITABLE_STRUCT(VkSparseImageFormatProperties2,sType,pNext,properties);

VISITABLE_STRUCT(VkPhysicalDeviceSparseImageFormatInfo2,sType,pNext,format,type,samples,usage,tiling);

VISITABLE_STRUCT(VkPhysicalDevicePointClippingProperties,sType,pNext,pointClippingBehavior);

VISITABLE_STRUCT(VkInputAttachmentAspectReference,subpass,inputAttachmentIndex,aspectMask);

VISITABLE_STRUCT(VkRenderPassInputAttachmentAspectCreateInfo,sType,pNext,aspectReferenceCount,pAspectReferences);

VISITABLE_STRUCT(VkImageViewUsageCreateInfo,sType,pNext,usage);

VISITABLE_STRUCT(VkPipelineTessellationDomainOriginStateCreateInfo,sType,pNext,domainOrigin);

VISITABLE_STRUCT(VkRenderPassMultiviewCreateInfo,sType,pNext,subpassCount,pViewMasks,dependencyCount,pViewOffsets,correlationMaskCount,pCorrelationMasks);

VISITABLE_STRUCT(VkPhysicalDeviceMultiviewFeatures,sType,pNext,multiview,multiviewGeometryShader,multiviewTessellationShader);

VISITABLE_STRUCT(VkPhysicalDeviceMultiviewProperties,sType,pNext,maxMultiviewViewCount,maxMultiviewInstanceIndex);

VISITABLE_STRUCT(VkPhysicalDeviceVariablePointersFeatures,sType,pNext,variablePointersStorageBuffer,variablePointers);

VISITABLE_STRUCT(VkPhysicalDeviceProtectedMemoryFeatures,sType,pNext,protectedMemory);

VISITABLE_STRUCT(VkPhysicalDeviceProtectedMemoryProperties,sType,pNext,protectedNoFault);

VISITABLE_STRUCT(VkDeviceQueueInfo2,sType,pNext,flags,queueFamilyIndex,queueIndex);

VISITABLE_STRUCT(VkProtectedSubmitInfo,sType,pNext,protectedSubmit);

VISITABLE_STRUCT(VkSamplerYcbcrConversionCreateInfo,sType,pNext,format,ycbcrModel,ycbcrRange,components,xChromaOffset,yChromaOffset,chromaFilter,forceExplicitReconstruction);

VISITABLE_STRUCT(VkSamplerYcbcrConversionInfo,sType,pNext,conversion);

VISITABLE_STRUCT(VkBindImagePlaneMemoryInfo,sType,pNext,planeAspect);

VISITABLE_STRUCT(VkImagePlaneMemoryRequirementsInfo,sType,pNext,planeAspect);

VISITABLE_STRUCT(VkPhysicalDeviceSamplerYcbcrConversionFeatures,sType,pNext,samplerYcbcrConversion);

VISITABLE_STRUCT(VkSamplerYcbcrConversionImageFormatProperties,sType,pNext,combinedImageSamplerDescriptorCount);

VISITABLE_STRUCT(VkDescriptorUpdateTemplateEntry,dstBinding,dstArrayElement,descriptorCount,descriptorType,offset,stride);

VISITABLE_STRUCT(VkDescriptorUpdateTemplateCreateInfo,sType,pNext,flags,descriptorUpdateEntryCount,pDescriptorUpdateEntries,templateType,descriptorSetLayout,pipelineBindPoint,pipelineLayout,set);

VISITABLE_STRUCT(VkExternalMemoryProperties,externalMemoryFeatures,exportFromImportedHandleTypes,compatibleHandleTypes);

VISITABLE_STRUCT(VkPhysicalDeviceExternalImageFormatInfo,sType,pNext,handleType);

VISITABLE_STRUCT(VkExternalImageFormatProperties,sType,pNext,externalMemoryProperties);

VISITABLE_STRUCT(VkPhysicalDeviceExternalBufferInfo,sType,pNext,flags,usage,handleType);

VISITABLE_STRUCT(VkExternalBufferProperties,sType,pNext,externalMemoryProperties);

VISITABLE_STRUCT(VkPhysicalDeviceIDProperties,sType,pNext,deviceUUID,driverUUID,deviceLUID,deviceNodeMask,deviceLUIDValid);

VISITABLE_STRUCT(VkExternalMemoryImageCreateInfo,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkExternalMemoryBufferCreateInfo,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkExportMemoryAllocateInfo,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkPhysicalDeviceExternalFenceInfo,sType,pNext,handleType);

VISITABLE_STRUCT(VkExternalFenceProperties,sType,pNext,exportFromImportedHandleTypes,compatibleHandleTypes,externalFenceFeatures);

VISITABLE_STRUCT(VkExportFenceCreateInfo,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkExportSemaphoreCreateInfo,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkPhysicalDeviceExternalSemaphoreInfo,sType,pNext,handleType);

VISITABLE_STRUCT(VkExternalSemaphoreProperties,sType,pNext,exportFromImportedHandleTypes,compatibleHandleTypes,externalSemaphoreFeatures);

VISITABLE_STRUCT(VkPhysicalDeviceMaintenance3Properties,sType,pNext,maxPerSetDescriptors,maxMemoryAllocationSize);

VISITABLE_STRUCT(VkDescriptorSetLayoutSupport,sType,pNext,supported);

VISITABLE_STRUCT(VkPhysicalDeviceShaderDrawParametersFeatures,sType,pNext,shaderDrawParameters);

VISITABLE_STRUCT(VkSurfaceCapabilitiesKHR,minImageCount,maxImageCount,currentExtent,minImageExtent,maxImageExtent,maxImageArrayLayers,supportedTransforms,currentTransform,supportedCompositeAlpha,supportedUsageFlags);

VISITABLE_STRUCT(VkSurfaceFormatKHR,format,colorSpace);

VISITABLE_STRUCT(VkSwapchainCreateInfoKHR,sType,pNext,flags,surface,minImageCount,imageFormat,imageColorSpace,imageExtent,imageArrayLayers,imageUsage,imageSharingMode,queueFamilyIndexCount,pQueueFamilyIndices,preTransform,compositeAlpha,presentMode,clipped,oldSwapchain);

VISITABLE_STRUCT(VkPresentInfoKHR,sType,pNext,waitSemaphoreCount,pWaitSemaphores,swapchainCount,pSwapchains,pImageIndices,pResults);

VISITABLE_STRUCT(VkImageSwapchainCreateInfoKHR,sType,pNext,swapchain);

VISITABLE_STRUCT(VkBindImageMemorySwapchainInfoKHR,sType,pNext,swapchain,imageIndex);

VISITABLE_STRUCT(VkAcquireNextImageInfoKHR,sType,pNext,swapchain,timeout,semaphore,fence,deviceMask);

VISITABLE_STRUCT(VkDeviceGroupPresentCapabilitiesKHR,sType,pNext,presentMask,modes);

VISITABLE_STRUCT(VkDeviceGroupPresentInfoKHR,sType,pNext,swapchainCount,pDeviceMasks,mode);

VISITABLE_STRUCT(VkDeviceGroupSwapchainCreateInfoKHR,sType,pNext,modes);

VISITABLE_STRUCT(VkDisplayPropertiesKHR,display,displayName,physicalDimensions,physicalResolution,supportedTransforms,planeReorderPossible,persistentContent);

VISITABLE_STRUCT(VkDisplayModeParametersKHR,visibleRegion,refreshRate);

VISITABLE_STRUCT(VkDisplayModePropertiesKHR,displayMode,parameters);

VISITABLE_STRUCT(VkDisplayModeCreateInfoKHR,sType,pNext,flags,parameters);

VISITABLE_STRUCT(VkDisplayPlaneCapabilitiesKHR,supportedAlpha,minSrcPosition,maxSrcPosition,minSrcExtent,maxSrcExtent,minDstPosition,maxDstPosition,minDstExtent,maxDstExtent);

VISITABLE_STRUCT(VkDisplayPlanePropertiesKHR,currentDisplay,currentStackIndex);

VISITABLE_STRUCT(VkDisplaySurfaceCreateInfoKHR,sType,pNext,flags,displayMode,planeIndex,planeStackIndex,transform,globalAlpha,alphaMode,imageExtent);

VISITABLE_STRUCT(VkDisplayPresentInfoKHR,sType,pNext,srcRect,dstRect,persistent);

VISITABLE_STRUCT(VkImportMemoryFdInfoKHR,sType,pNext,handleType,fd);

VISITABLE_STRUCT(VkMemoryFdPropertiesKHR,sType,pNext,memoryTypeBits);

VISITABLE_STRUCT(VkMemoryGetFdInfoKHR,sType,pNext,memory,handleType);

VISITABLE_STRUCT(VkImportSemaphoreFdInfoKHR,sType,pNext,semaphore,flags,handleType,fd);

VISITABLE_STRUCT(VkSemaphoreGetFdInfoKHR,sType,pNext,semaphore,handleType);

VISITABLE_STRUCT(VkPhysicalDevicePushDescriptorPropertiesKHR,sType,pNext,maxPushDescriptors);

VISITABLE_STRUCT(VkPhysicalDeviceShaderFloat16Int8FeaturesKHR,sType,pNext,shaderFloat16,shaderInt8);

VISITABLE_STRUCT(VkRectLayerKHR,offset,extent,layer);

VISITABLE_STRUCT(VkPresentRegionKHR,rectangleCount,pRectangles);

VISITABLE_STRUCT(VkPresentRegionsKHR,sType,pNext,swapchainCount,pRegions);

VISITABLE_STRUCT(VkPhysicalDeviceImagelessFramebufferFeaturesKHR,sType,pNext,imagelessFramebuffer);

VISITABLE_STRUCT(VkFramebufferAttachmentImageInfoKHR,sType,pNext,flags,usage,width,height,layerCount,viewFormatCount,pViewFormats);

VISITABLE_STRUCT(VkFramebufferAttachmentsCreateInfoKHR,sType,pNext,attachmentImageInfoCount,pAttachmentImageInfos);

VISITABLE_STRUCT(VkRenderPassAttachmentBeginInfoKHR,sType,pNext,attachmentCount,pAttachments);

VISITABLE_STRUCT(VkAttachmentDescription2KHR,sType,pNext,flags,format,samples,loadOp,storeOp,stencilLoadOp,stencilStoreOp,initialLayout,finalLayout);

VISITABLE_STRUCT(VkAttachmentReference2KHR,sType,pNext,attachment,layout,aspectMask);

VISITABLE_STRUCT(VkSubpassDescription2KHR,sType,pNext,flags,pipelineBindPoint,viewMask,inputAttachmentCount,pInputAttachments,colorAttachmentCount,pColorAttachments,pResolveAttachments,pDepthStencilAttachment,preserveAttachmentCount,pPreserveAttachments);

VISITABLE_STRUCT(VkSubpassDependency2KHR,sType,pNext,srcSubpass,dstSubpass,srcStageMask,dstStageMask,srcAccessMask,dstAccessMask,dependencyFlags,viewOffset);

VISITABLE_STRUCT(VkRenderPassCreateInfo2KHR,sType,pNext,flags,attachmentCount,pAttachments,subpassCount,pSubpasses,dependencyCount,pDependencies,correlatedViewMaskCount,pCorrelatedViewMasks);

VISITABLE_STRUCT(VkSubpassBeginInfoKHR,sType,pNext,contents);

VISITABLE_STRUCT(VkSubpassEndInfoKHR,sType,pNext);

VISITABLE_STRUCT(VkSharedPresentSurfaceCapabilitiesKHR,sType,pNext,sharedPresentSupportedUsageFlags);

VISITABLE_STRUCT(VkImportFenceFdInfoKHR,sType,pNext,fence,flags,handleType,fd);

VISITABLE_STRUCT(VkFenceGetFdInfoKHR,sType,pNext,fence,handleType);

VISITABLE_STRUCT(VkPhysicalDeviceSurfaceInfo2KHR,sType,pNext,surface);

VISITABLE_STRUCT(VkSurfaceCapabilities2KHR,sType,pNext,surfaceCapabilities);

VISITABLE_STRUCT(VkSurfaceFormat2KHR,sType,pNext,surfaceFormat);

VISITABLE_STRUCT(VkDisplayProperties2KHR,sType,pNext,displayProperties);

VISITABLE_STRUCT(VkDisplayPlaneProperties2KHR,sType,pNext,displayPlaneProperties);

VISITABLE_STRUCT(VkDisplayModeProperties2KHR,sType,pNext,displayModeProperties);

VISITABLE_STRUCT(VkDisplayPlaneInfo2KHR,sType,pNext,mode,planeIndex);

VISITABLE_STRUCT(VkDisplayPlaneCapabilities2KHR,sType,pNext,capabilities);

VISITABLE_STRUCT(VkImageFormatListCreateInfoKHR,sType,pNext,viewFormatCount,pViewFormats);

VISITABLE_STRUCT(VkPhysicalDeviceShaderSubgroupExtendedTypesFeaturesKHR,sType,pNext,shaderSubgroupExtendedTypes);

VISITABLE_STRUCT(VkPhysicalDevice8BitStorageFeaturesKHR,sType,pNext,storageBuffer8BitAccess,uniformAndStorageBuffer8BitAccess,storagePushConstant8);

VISITABLE_STRUCT(VkPhysicalDeviceShaderAtomicInt64FeaturesKHR,sType,pNext,shaderBufferInt64Atomics,shaderSharedInt64Atomics);

VISITABLE_STRUCT(VkPhysicalDeviceShaderClockFeaturesKHR,sType,pNext,shaderSubgroupClock,shaderDeviceClock);

VISITABLE_STRUCT(VkConformanceVersionKHR,major,minor,subminor,patch);

VISITABLE_STRUCT(VkPhysicalDeviceDriverPropertiesKHR,sType,pNext,driverID,driverName,driverInfo,conformanceVersion);

VISITABLE_STRUCT(VkPhysicalDeviceFloatControlsPropertiesKHR,sType,pNext,denormBehaviorIndependence,roundingModeIndependence,shaderSignedZeroInfNanPreserveFloat16,shaderSignedZeroInfNanPreserveFloat32,shaderSignedZeroInfNanPreserveFloat64,shaderDenormPreserveFloat16,shaderDenormPreserveFloat32,shaderDenormPreserveFloat64,shaderDenormFlushToZeroFloat16,shaderDenormFlushToZeroFloat32,shaderDenormFlushToZeroFloat64,shaderRoundingModeRTEFloat16,shaderRoundingModeRTEFloat32,shaderRoundingModeRTEFloat64,shaderRoundingModeRTZFloat16,shaderRoundingModeRTZFloat32,shaderRoundingModeRTZFloat64);

VISITABLE_STRUCT(VkSubpassDescriptionDepthStencilResolveKHR,sType,pNext,depthResolveMode,stencilResolveMode,pDepthStencilResolveAttachment);

VISITABLE_STRUCT(VkPhysicalDeviceDepthStencilResolvePropertiesKHR,sType,pNext,supportedDepthResolveModes,supportedStencilResolveModes,independentResolveNone,independentResolve);

VISITABLE_STRUCT(VkPhysicalDeviceTimelineSemaphoreFeaturesKHR,sType,pNext,timelineSemaphore);

VISITABLE_STRUCT(VkPhysicalDeviceTimelineSemaphorePropertiesKHR,sType,pNext,maxTimelineSemaphoreValueDifference);

VISITABLE_STRUCT(VkSemaphoreTypeCreateInfoKHR,sType,pNext,semaphoreType,initialValue);

VISITABLE_STRUCT(VkTimelineSemaphoreSubmitInfoKHR,sType,pNext,waitSemaphoreValueCount,pWaitSemaphoreValues,signalSemaphoreValueCount,pSignalSemaphoreValues);

VISITABLE_STRUCT(VkSemaphoreWaitInfoKHR,sType,pNext,flags,semaphoreCount,pSemaphores,pValues);

VISITABLE_STRUCT(VkSemaphoreSignalInfoKHR,sType,pNext,semaphore,value);

VISITABLE_STRUCT(VkPhysicalDeviceVulkanMemoryModelFeaturesKHR,sType,pNext,vulkanMemoryModel,vulkanMemoryModelDeviceScope,vulkanMemoryModelAvailabilityVisibilityChains);

VISITABLE_STRUCT(VkSurfaceProtectedCapabilitiesKHR,sType,pNext,supportsProtected);

VISITABLE_STRUCT(VkPhysicalDeviceUniformBufferStandardLayoutFeaturesKHR,sType,pNext,uniformBufferStandardLayout);

VISITABLE_STRUCT(VkPhysicalDevicePipelineExecutablePropertiesFeaturesKHR,sType,pNext,pipelineExecutableInfo);

VISITABLE_STRUCT(VkPipelineInfoKHR,sType,pNext,pipeline);

VISITABLE_STRUCT(VkPipelineExecutablePropertiesKHR,sType,pNext,stages,name,description,subgroupSize);

VISITABLE_STRUCT(VkPipelineExecutableInfoKHR,sType,pNext,pipeline,executableIndex);

VISITABLE_STRUCT(VkPipelineExecutableStatisticKHR,sType,pNext,name,description,format,value);

VISITABLE_STRUCT(VkPipelineExecutableInternalRepresentationKHR,sType,pNext,name,description,isText,dataSize,pData);

VISITABLE_STRUCT(VkDebugReportCallbackCreateInfoEXT,sType,pNext,flags,pfnCallback,pUserData);

VISITABLE_STRUCT(VkPipelineRasterizationStateRasterizationOrderAMD,sType,pNext,rasterizationOrder);

VISITABLE_STRUCT(VkDebugMarkerObjectNameInfoEXT,sType,pNext,objectType,object,pObjectName);

VISITABLE_STRUCT(VkDebugMarkerObjectTagInfoEXT,sType,pNext,objectType,object,tagName,tagSize,pTag);

VISITABLE_STRUCT(VkDebugMarkerMarkerInfoEXT,sType,pNext,pMarkerName,color);

VISITABLE_STRUCT(VkDedicatedAllocationImageCreateInfoNV,sType,pNext,dedicatedAllocation);

VISITABLE_STRUCT(VkDedicatedAllocationBufferCreateInfoNV,sType,pNext,dedicatedAllocation);

VISITABLE_STRUCT(VkDedicatedAllocationMemoryAllocateInfoNV,sType,pNext,image,buffer);

VISITABLE_STRUCT(VkPhysicalDeviceTransformFeedbackFeaturesEXT,sType,pNext,transformFeedback,geometryStreams);

VISITABLE_STRUCT(VkPhysicalDeviceTransformFeedbackPropertiesEXT,sType,pNext,maxTransformFeedbackStreams,maxTransformFeedbackBuffers,maxTransformFeedbackBufferSize,maxTransformFeedbackStreamDataSize,maxTransformFeedbackBufferDataSize,maxTransformFeedbackBufferDataStride,transformFeedbackQueries,transformFeedbackStreamsLinesTriangles,transformFeedbackRasterizationStreamSelect,transformFeedbackDraw);

VISITABLE_STRUCT(VkPipelineRasterizationStateStreamCreateInfoEXT,sType,pNext,flags,rasterizationStream);

VISITABLE_STRUCT(VkImageViewHandleInfoNVX,sType,pNext,imageView,descriptorType,sampler);

VISITABLE_STRUCT(VkTextureLODGatherFormatPropertiesAMD,sType,pNext,supportsTextureGatherLODBiasAMD);

VISITABLE_STRUCT(VkShaderResourceUsageAMD,numUsedVgprs,numUsedSgprs,ldsSizePerLocalWorkGroup,ldsUsageSizeInBytes,scratchMemUsageInBytes);

VISITABLE_STRUCT(VkShaderStatisticsInfoAMD,shaderStageMask,resourceUsage,numPhysicalVgprs,numPhysicalSgprs,numAvailableVgprs,numAvailableSgprs,computeWorkGroupSize);

VISITABLE_STRUCT(VkPhysicalDeviceCornerSampledImageFeaturesNV,sType,pNext,cornerSampledImage);

VISITABLE_STRUCT(VkExternalImageFormatPropertiesNV,imageFormatProperties,externalMemoryFeatures,exportFromImportedHandleTypes,compatibleHandleTypes);

VISITABLE_STRUCT(VkExternalMemoryImageCreateInfoNV,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkExportMemoryAllocateInfoNV,sType,pNext,handleTypes);

VISITABLE_STRUCT(VkValidationFlagsEXT,sType,pNext,disabledValidationCheckCount,pDisabledValidationChecks);

VISITABLE_STRUCT(VkPhysicalDeviceTextureCompressionASTCHDRFeaturesEXT,sType,pNext,textureCompressionASTC_HDR);

VISITABLE_STRUCT(VkImageViewASTCDecodeModeEXT,sType,pNext,decodeMode);

VISITABLE_STRUCT(VkPhysicalDeviceASTCDecodeFeaturesEXT,sType,pNext,decodeModeSharedExponent);

VISITABLE_STRUCT(VkConditionalRenderingBeginInfoEXT,sType,pNext,buffer,offset,flags);

VISITABLE_STRUCT(VkPhysicalDeviceConditionalRenderingFeaturesEXT,sType,pNext,conditionalRendering,inheritedConditionalRendering);

VISITABLE_STRUCT(VkCommandBufferInheritanceConditionalRenderingInfoEXT,sType,pNext,conditionalRenderingEnable);

VISITABLE_STRUCT(VkDeviceGeneratedCommandsFeaturesNVX,sType,pNext,computeBindingPointSupport);

VISITABLE_STRUCT(VkDeviceGeneratedCommandsLimitsNVX,sType,pNext,maxIndirectCommandsLayoutTokenCount,maxObjectEntryCounts,minSequenceCountBufferOffsetAlignment,minSequenceIndexBufferOffsetAlignment,minCommandsTokenBufferOffsetAlignment);

VISITABLE_STRUCT(VkIndirectCommandsTokenNVX,tokenType,buffer,offset);

VISITABLE_STRUCT(VkIndirectCommandsLayoutTokenNVX,tokenType,bindingUnit,dynamicCount,divisor);

VISITABLE_STRUCT(VkIndirectCommandsLayoutCreateInfoNVX,sType,pNext,pipelineBindPoint,flags,tokenCount,pTokens);

VISITABLE_STRUCT(VkCmdProcessCommandsInfoNVX,sType,pNext,objectTable,indirectCommandsLayout,indirectCommandsTokenCount,pIndirectCommandsTokens,maxSequencesCount,targetCommandBuffer,sequencesCountBuffer,sequencesCountOffset,sequencesIndexBuffer,sequencesIndexOffset);

VISITABLE_STRUCT(VkCmdReserveSpaceForCommandsInfoNVX,sType,pNext,objectTable,indirectCommandsLayout,maxSequencesCount);

VISITABLE_STRUCT(VkObjectTableCreateInfoNVX,sType,pNext,objectCount,pObjectEntryTypes,pObjectEntryCounts,pObjectEntryUsageFlags,maxUniformBuffersPerDescriptor,maxStorageBuffersPerDescriptor,maxStorageImagesPerDescriptor,maxSampledImagesPerDescriptor,maxPipelineLayouts);

VISITABLE_STRUCT(VkObjectTableEntryNVX,type,flags);

VISITABLE_STRUCT(VkObjectTablePipelineEntryNVX,type,flags,pipeline);

VISITABLE_STRUCT(VkObjectTableDescriptorSetEntryNVX,type,flags,pipelineLayout,descriptorSet);

VISITABLE_STRUCT(VkObjectTableVertexBufferEntryNVX,type,flags,buffer);

VISITABLE_STRUCT(VkObjectTableIndexBufferEntryNVX,type,flags,buffer,indexType);

VISITABLE_STRUCT(VkObjectTablePushConstantEntryNVX,type,flags,pipelineLayout,stageFlags);

VISITABLE_STRUCT(VkViewportWScalingNV,xcoeff,ycoeff);

VISITABLE_STRUCT(VkPipelineViewportWScalingStateCreateInfoNV,sType,pNext,viewportWScalingEnable,viewportCount,pViewportWScalings);

VISITABLE_STRUCT(VkSurfaceCapabilities2EXT,sType,pNext,minImageCount,maxImageCount,currentExtent,minImageExtent,maxImageExtent,maxImageArrayLayers,supportedTransforms,currentTransform,supportedCompositeAlpha,supportedUsageFlags,supportedSurfaceCounters);

VISITABLE_STRUCT(VkDisplayPowerInfoEXT,sType,pNext,powerState);

VISITABLE_STRUCT(VkDeviceEventInfoEXT,sType,pNext,deviceEvent);

VISITABLE_STRUCT(VkDisplayEventInfoEXT,sType,pNext,displayEvent);

VISITABLE_STRUCT(VkSwapchainCounterCreateInfoEXT,sType,pNext,surfaceCounters);

VISITABLE_STRUCT(VkRefreshCycleDurationGOOGLE,refreshDuration);

VISITABLE_STRUCT(VkPastPresentationTimingGOOGLE,presentID,desiredPresentTime,actualPresentTime,earliestPresentTime,presentMargin);

VISITABLE_STRUCT(VkPresentTimeGOOGLE,presentID,desiredPresentTime);

VISITABLE_STRUCT(VkPresentTimesInfoGOOGLE,sType,pNext,swapchainCount,pTimes);

VISITABLE_STRUCT(VkPhysicalDeviceMultiviewPerViewAttributesPropertiesNVX,sType,pNext,perViewPositionAllComponents);

VISITABLE_STRUCT(VkViewportSwizzleNV,x,y,z,w);

VISITABLE_STRUCT(VkPipelineViewportSwizzleStateCreateInfoNV,sType,pNext,flags,viewportCount,pViewportSwizzles);

VISITABLE_STRUCT(VkPhysicalDeviceDiscardRectanglePropertiesEXT,sType,pNext,maxDiscardRectangles);

VISITABLE_STRUCT(VkPipelineDiscardRectangleStateCreateInfoEXT,sType,pNext,flags,discardRectangleMode,discardRectangleCount,pDiscardRectangles);

VISITABLE_STRUCT(VkPhysicalDeviceConservativeRasterizationPropertiesEXT,sType,pNext,primitiveOverestimationSize,maxExtraPrimitiveOverestimationSize,extraPrimitiveOverestimationSizeGranularity,primitiveUnderestimation,conservativePointAndLineRasterization,degenerateTrianglesRasterized,degenerateLinesRasterized,fullyCoveredFragmentShaderInputVariable,conservativeRasterizationPostDepthCoverage);

VISITABLE_STRUCT(VkPipelineRasterizationConservativeStateCreateInfoEXT,sType,pNext,flags,conservativeRasterizationMode,extraPrimitiveOverestimationSize);

VISITABLE_STRUCT(VkPhysicalDeviceDepthClipEnableFeaturesEXT,sType,pNext,depthClipEnable);

VISITABLE_STRUCT(VkPipelineRasterizationDepthClipStateCreateInfoEXT,sType,pNext,flags,depthClipEnable);

VISITABLE_STRUCT(VkXYColorEXT,x,y);

VISITABLE_STRUCT(VkHdrMetadataEXT,sType,pNext,displayPrimaryRed,displayPrimaryGreen,displayPrimaryBlue,whitePoint,maxLuminance,minLuminance,maxContentLightLevel,maxFrameAverageLightLevel);

VISITABLE_STRUCT(VkDebugUtilsObjectNameInfoEXT,sType,pNext,objectType,objectHandle,pObjectName);

VISITABLE_STRUCT(VkDebugUtilsObjectTagInfoEXT,sType,pNext,objectType,objectHandle,tagName,tagSize,pTag);

VISITABLE_STRUCT(VkDebugUtilsLabelEXT,sType,pNext,pLabelName,color);

VISITABLE_STRUCT(VkDebugUtilsMessengerCallbackDataEXT,sType,pNext,flags,pMessageIdName,messageIdNumber,pMessage,queueLabelCount,pQueueLabels,cmdBufLabelCount,pCmdBufLabels,objectCount,pObjects);

VISITABLE_STRUCT(VkDebugUtilsMessengerCreateInfoEXT,sType,pNext,flags,messageSeverity,messageType,pfnUserCallback,pUserData);

VISITABLE_STRUCT(VkSamplerReductionModeCreateInfoEXT,sType,pNext,reductionMode);

VISITABLE_STRUCT(VkPhysicalDeviceSamplerFilterMinmaxPropertiesEXT,sType,pNext,filterMinmaxSingleComponentFormats,filterMinmaxImageComponentMapping);

VISITABLE_STRUCT(VkPhysicalDeviceInlineUniformBlockFeaturesEXT,sType,pNext,inlineUniformBlock,descriptorBindingInlineUniformBlockUpdateAfterBind);

VISITABLE_STRUCT(VkPhysicalDeviceInlineUniformBlockPropertiesEXT,sType,pNext,maxInlineUniformBlockSize,maxPerStageDescriptorInlineUniformBlocks,maxPerStageDescriptorUpdateAfterBindInlineUniformBlocks,maxDescriptorSetInlineUniformBlocks,maxDescriptorSetUpdateAfterBindInlineUniformBlocks);

VISITABLE_STRUCT(VkWriteDescriptorSetInlineUniformBlockEXT,sType,pNext,dataSize,pData);

VISITABLE_STRUCT(VkDescriptorPoolInlineUniformBlockCreateInfoEXT,sType,pNext,maxInlineUniformBlockBindings);

VISITABLE_STRUCT(VkSampleLocationEXT,x,y);

VISITABLE_STRUCT(VkSampleLocationsInfoEXT,sType,pNext,sampleLocationsPerPixel,sampleLocationGridSize,sampleLocationsCount,pSampleLocations);

VISITABLE_STRUCT(VkAttachmentSampleLocationsEXT,attachmentIndex,sampleLocationsInfo);

VISITABLE_STRUCT(VkSubpassSampleLocationsEXT,subpassIndex,sampleLocationsInfo);

VISITABLE_STRUCT(VkRenderPassSampleLocationsBeginInfoEXT,sType,pNext,attachmentInitialSampleLocationsCount,pAttachmentInitialSampleLocations,postSubpassSampleLocationsCount,pPostSubpassSampleLocations);

VISITABLE_STRUCT(VkPipelineSampleLocationsStateCreateInfoEXT,sType,pNext,sampleLocationsEnable,sampleLocationsInfo);

VISITABLE_STRUCT(VkPhysicalDeviceSampleLocationsPropertiesEXT,sType,pNext,sampleLocationSampleCounts,maxSampleLocationGridSize,sampleLocationCoordinateRange,sampleLocationSubPixelBits,variableSampleLocations);

VISITABLE_STRUCT(VkMultisamplePropertiesEXT,sType,pNext,maxSampleLocationGridSize);

VISITABLE_STRUCT(VkPhysicalDeviceBlendOperationAdvancedFeaturesEXT,sType,pNext,advancedBlendCoherentOperations);

VISITABLE_STRUCT(VkPhysicalDeviceBlendOperationAdvancedPropertiesEXT,sType,pNext,advancedBlendMaxColorAttachments,advancedBlendIndependentBlend,advancedBlendNonPremultipliedSrcColor,advancedBlendNonPremultipliedDstColor,advancedBlendCorrelatedOverlap,advancedBlendAllOperations);

VISITABLE_STRUCT(VkPipelineColorBlendAdvancedStateCreateInfoEXT,sType,pNext,srcPremultiplied,dstPremultiplied,blendOverlap);

VISITABLE_STRUCT(VkPipelineCoverageToColorStateCreateInfoNV,sType,pNext,flags,coverageToColorEnable,coverageToColorLocation);

VISITABLE_STRUCT(VkPipelineCoverageModulationStateCreateInfoNV,sType,pNext,flags,coverageModulationMode,coverageModulationTableEnable,coverageModulationTableCount,pCoverageModulationTable);

VISITABLE_STRUCT(VkPhysicalDeviceShaderSMBuiltinsPropertiesNV,sType,pNext,shaderSMCount,shaderWarpsPerSM);

VISITABLE_STRUCT(VkPhysicalDeviceShaderSMBuiltinsFeaturesNV,sType,pNext,shaderSMBuiltins);

VISITABLE_STRUCT(VkDrmFormatModifierPropertiesEXT,drmFormatModifier,drmFormatModifierPlaneCount,drmFormatModifierTilingFeatures);

VISITABLE_STRUCT(VkDrmFormatModifierPropertiesListEXT,sType,pNext,drmFormatModifierCount,pDrmFormatModifierProperties);

VISITABLE_STRUCT(VkPhysicalDeviceImageDrmFormatModifierInfoEXT,sType,pNext,drmFormatModifier,sharingMode,queueFamilyIndexCount,pQueueFamilyIndices);

VISITABLE_STRUCT(VkImageDrmFormatModifierListCreateInfoEXT,sType,pNext,drmFormatModifierCount,pDrmFormatModifiers);

VISITABLE_STRUCT(VkImageDrmFormatModifierExplicitCreateInfoEXT,sType,pNext,drmFormatModifier,drmFormatModifierPlaneCount,pPlaneLayouts);

VISITABLE_STRUCT(VkImageDrmFormatModifierPropertiesEXT,sType,pNext,drmFormatModifier);

VISITABLE_STRUCT(VkValidationCacheCreateInfoEXT,sType,pNext,flags,initialDataSize,pInitialData);

VISITABLE_STRUCT(VkShaderModuleValidationCacheCreateInfoEXT,sType,pNext,validationCache);

VISITABLE_STRUCT(VkDescriptorSetLayoutBindingFlagsCreateInfoEXT,sType,pNext,bindingCount,pBindingFlags);

VISITABLE_STRUCT(VkPhysicalDeviceDescriptorIndexingFeaturesEXT,sType,pNext,shaderInputAttachmentArrayDynamicIndexing,shaderUniformTexelBufferArrayDynamicIndexing,shaderStorageTexelBufferArrayDynamicIndexing,shaderUniformBufferArrayNonUniformIndexing,shaderSampledImageArrayNonUniformIndexing,shaderStorageBufferArrayNonUniformIndexing,shaderStorageImageArrayNonUniformIndexing,shaderInputAttachmentArrayNonUniformIndexing,shaderUniformTexelBufferArrayNonUniformIndexing,shaderStorageTexelBufferArrayNonUniformIndexing,descriptorBindingUniformBufferUpdateAfterBind,descriptorBindingSampledImageUpdateAfterBind,descriptorBindingStorageImageUpdateAfterBind,descriptorBindingStorageBufferUpdateAfterBind,descriptorBindingUniformTexelBufferUpdateAfterBind,descriptorBindingStorageTexelBufferUpdateAfterBind,descriptorBindingUpdateUnusedWhilePending,descriptorBindingPartiallyBound,descriptorBindingVariableDescriptorCount,runtimeDescriptorArray);

VISITABLE_STRUCT(VkPhysicalDeviceDescriptorIndexingPropertiesEXT,sType,pNext,maxUpdateAfterBindDescriptorsInAllPools,shaderUniformBufferArrayNonUniformIndexingNative,shaderSampledImageArrayNonUniformIndexingNative,shaderStorageBufferArrayNonUniformIndexingNative,shaderStorageImageArrayNonUniformIndexingNative,shaderInputAttachmentArrayNonUniformIndexingNative,robustBufferAccessUpdateAfterBind,quadDivergentImplicitLod,maxPerStageDescriptorUpdateAfterBindSamplers,maxPerStageDescriptorUpdateAfterBindUniformBuffers,maxPerStageDescriptorUpdateAfterBindStorageBuffers,maxPerStageDescriptorUpdateAfterBindSampledImages,maxPerStageDescriptorUpdateAfterBindStorageImages,maxPerStageDescriptorUpdateAfterBindInputAttachments,maxPerStageUpdateAfterBindResources,maxDescriptorSetUpdateAfterBindSamplers,maxDescriptorSetUpdateAfterBindUniformBuffers,maxDescriptorSetUpdateAfterBindUniformBuffersDynamic,maxDescriptorSetUpdateAfterBindStorageBuffers,maxDescriptorSetUpdateAfterBindStorageBuffersDynamic,maxDescriptorSetUpdateAfterBindSampledImages,maxDescriptorSetUpdateAfterBindStorageImages,maxDescriptorSetUpdateAfterBindInputAttachments);

VISITABLE_STRUCT(VkDescriptorSetVariableDescriptorCountAllocateInfoEXT,sType,pNext,descriptorSetCount,pDescriptorCounts);

VISITABLE_STRUCT(VkDescriptorSetVariableDescriptorCountLayoutSupportEXT,sType,pNext,maxVariableDescriptorCount);

VISITABLE_STRUCT(VkShadingRatePaletteNV,shadingRatePaletteEntryCount,pShadingRatePaletteEntries);

VISITABLE_STRUCT(VkPipelineViewportShadingRateImageStateCreateInfoNV,sType,pNext,shadingRateImageEnable,viewportCount,pShadingRatePalettes);

VISITABLE_STRUCT(VkPhysicalDeviceShadingRateImageFeaturesNV,sType,pNext,shadingRateImage,shadingRateCoarseSampleOrder);

VISITABLE_STRUCT(VkPhysicalDeviceShadingRateImagePropertiesNV,sType,pNext,shadingRateTexelSize,shadingRatePaletteSize,shadingRateMaxCoarseSamples);

VISITABLE_STRUCT(VkCoarseSampleLocationNV,pixelX,pixelY,sample);

VISITABLE_STRUCT(VkCoarseSampleOrderCustomNV,shadingRate,sampleCount,sampleLocationCount,pSampleLocations);

VISITABLE_STRUCT(VkPipelineViewportCoarseSampleOrderStateCreateInfoNV,sType,pNext,sampleOrderType,customSampleOrderCount,pCustomSampleOrders);

VISITABLE_STRUCT(VkRayTracingShaderGroupCreateInfoNV,sType,pNext,type,generalShader,closestHitShader,anyHitShader,intersectionShader);

VISITABLE_STRUCT(VkRayTracingPipelineCreateInfoNV,sType,pNext,flags,stageCount,pStages,groupCount,pGroups,maxRecursionDepth,layout,basePipelineHandle,basePipelineIndex);

VISITABLE_STRUCT(VkGeometryTrianglesNV,sType,pNext,vertexData,vertexOffset,vertexCount,vertexStride,vertexFormat,indexData,indexOffset,indexCount,indexType,transformData,transformOffset);

VISITABLE_STRUCT(VkGeometryAABBNV,sType,pNext,aabbData,numAABBs,stride,offset);

VISITABLE_STRUCT(VkGeometryDataNV,triangles,aabbs);

VISITABLE_STRUCT(VkGeometryNV,sType,pNext,geometryType,geometry,flags);

VISITABLE_STRUCT(VkAccelerationStructureInfoNV,sType,pNext,type,flags,instanceCount,geometryCount,pGeometries);

VISITABLE_STRUCT(VkAccelerationStructureCreateInfoNV,sType,pNext,compactedSize,info);

VISITABLE_STRUCT(VkBindAccelerationStructureMemoryInfoNV,sType,pNext,accelerationStructure,memory,memoryOffset,deviceIndexCount,pDeviceIndices);

VISITABLE_STRUCT(VkWriteDescriptorSetAccelerationStructureNV,sType,pNext,accelerationStructureCount,pAccelerationStructures);

VISITABLE_STRUCT(VkAccelerationStructureMemoryRequirementsInfoNV,sType,pNext,type,accelerationStructure);

VISITABLE_STRUCT(VkPhysicalDeviceRayTracingPropertiesNV,sType,pNext,shaderGroupHandleSize,maxRecursionDepth,maxShaderGroupStride,shaderGroupBaseAlignment,maxGeometryCount,maxInstanceCount,maxTriangleCount,maxDescriptorSetAccelerationStructures);

VISITABLE_STRUCT(VkPhysicalDeviceRepresentativeFragmentTestFeaturesNV,sType,pNext,representativeFragmentTest);

VISITABLE_STRUCT(VkPipelineRepresentativeFragmentTestStateCreateInfoNV,sType,pNext,representativeFragmentTestEnable);

VISITABLE_STRUCT(VkPhysicalDeviceImageViewImageFormatInfoEXT,sType,pNext,imageViewType);

VISITABLE_STRUCT(VkFilterCubicImageViewImageFormatPropertiesEXT,sType,pNext,filterCubic,filterCubicMinmax);

VISITABLE_STRUCT(VkDeviceQueueGlobalPriorityCreateInfoEXT,sType,pNext,globalPriority);

VISITABLE_STRUCT(VkImportMemoryHostPointerInfoEXT,sType,pNext,handleType,pHostPointer);

VISITABLE_STRUCT(VkMemoryHostPointerPropertiesEXT,sType,pNext,memoryTypeBits);

VISITABLE_STRUCT(VkPhysicalDeviceExternalMemoryHostPropertiesEXT,sType,pNext,minImportedHostPointerAlignment);

VISITABLE_STRUCT(VkPipelineCompilerControlCreateInfoAMD,sType,pNext,compilerControlFlags);

VISITABLE_STRUCT(VkCalibratedTimestampInfoEXT,sType,pNext,timeDomain);

VISITABLE_STRUCT(VkPhysicalDeviceShaderCorePropertiesAMD,sType,pNext,shaderEngineCount,shaderArraysPerEngineCount,computeUnitsPerShaderArray,simdPerComputeUnit,wavefrontsPerSimd,wavefrontSize,sgprsPerSimd,minSgprAllocation,maxSgprAllocation,sgprAllocationGranularity,vgprsPerSimd,minVgprAllocation,maxVgprAllocation,vgprAllocationGranularity);

VISITABLE_STRUCT(VkDeviceMemoryOverallocationCreateInfoAMD,sType,pNext,overallocationBehavior);

VISITABLE_STRUCT(VkPhysicalDeviceVertexAttributeDivisorPropertiesEXT,sType,pNext,maxVertexAttribDivisor);

VISITABLE_STRUCT(VkVertexInputBindingDivisorDescriptionEXT,binding,divisor);

VISITABLE_STRUCT(VkPipelineVertexInputDivisorStateCreateInfoEXT,sType,pNext,vertexBindingDivisorCount,pVertexBindingDivisors);

VISITABLE_STRUCT(VkPhysicalDeviceVertexAttributeDivisorFeaturesEXT,sType,pNext,vertexAttributeInstanceRateDivisor,vertexAttributeInstanceRateZeroDivisor);

VISITABLE_STRUCT(VkPipelineCreationFeedbackEXT,flags,duration);

VISITABLE_STRUCT(VkPipelineCreationFeedbackCreateInfoEXT,sType,pNext,pPipelineCreationFeedback,pipelineStageCreationFeedbackCount,pPipelineStageCreationFeedbacks);

VISITABLE_STRUCT(VkPhysicalDeviceComputeShaderDerivativesFeaturesNV,sType,pNext,computeDerivativeGroupQuads,computeDerivativeGroupLinear);

VISITABLE_STRUCT(VkPhysicalDeviceMeshShaderFeaturesNV,sType,pNext,taskShader,meshShader);

VISITABLE_STRUCT(VkPhysicalDeviceMeshShaderPropertiesNV,sType,pNext,maxDrawMeshTasksCount,maxTaskWorkGroupInvocations,maxTaskWorkGroupSize,maxTaskTotalMemorySize,maxTaskOutputCount,maxMeshWorkGroupInvocations,maxMeshWorkGroupSize,maxMeshTotalMemorySize,maxMeshOutputVertices,maxMeshOutputPrimitives,maxMeshMultiviewViewCount,meshOutputPerVertexGranularity,meshOutputPerPrimitiveGranularity);

VISITABLE_STRUCT(VkDrawMeshTasksIndirectCommandNV,taskCount,firstTask);

VISITABLE_STRUCT(VkPhysicalDeviceFragmentShaderBarycentricFeaturesNV,sType,pNext,fragmentShaderBarycentric);

VISITABLE_STRUCT(VkPhysicalDeviceShaderImageFootprintFeaturesNV,sType,pNext,imageFootprint);

VISITABLE_STRUCT(VkPipelineViewportExclusiveScissorStateCreateInfoNV,sType,pNext,exclusiveScissorCount,pExclusiveScissors);

VISITABLE_STRUCT(VkPhysicalDeviceExclusiveScissorFeaturesNV,sType,pNext,exclusiveScissor);

VISITABLE_STRUCT(VkQueueFamilyCheckpointPropertiesNV,sType,pNext,checkpointExecutionStageMask);

VISITABLE_STRUCT(VkCheckpointDataNV,sType,pNext,stage,pCheckpointMarker);

VISITABLE_STRUCT(VkPhysicalDeviceShaderIntegerFunctions2FeaturesINTEL,sType,pNext,shaderIntegerFunctions2);

VISITABLE_STRUCT(VkPerformanceValueINTEL,type,data);

VISITABLE_STRUCT(VkInitializePerformanceApiInfoINTEL,sType,pNext,pUserData);

VISITABLE_STRUCT(VkQueryPoolCreateInfoINTEL,sType,pNext,performanceCountersSampling);

VISITABLE_STRUCT(VkPerformanceMarkerInfoINTEL,sType,pNext,marker);

VISITABLE_STRUCT(VkPerformanceStreamMarkerInfoINTEL,sType,pNext,marker);

VISITABLE_STRUCT(VkPerformanceOverrideInfoINTEL,sType,pNext,type,enable,parameter);

VISITABLE_STRUCT(VkPerformanceConfigurationAcquireInfoINTEL,sType,pNext,type);

VISITABLE_STRUCT(VkPhysicalDevicePCIBusInfoPropertiesEXT,sType,pNext,pciDomain,pciBus,pciDevice,pciFunction);

VISITABLE_STRUCT(VkDisplayNativeHdrSurfaceCapabilitiesAMD,sType,pNext,localDimmingSupport);

VISITABLE_STRUCT(VkSwapchainDisplayNativeHdrCreateInfoAMD,sType,pNext,localDimmingEnable);

VISITABLE_STRUCT(VkPhysicalDeviceFragmentDensityMapFeaturesEXT,sType,pNext,fragmentDensityMap,fragmentDensityMapDynamic,fragmentDensityMapNonSubsampledImages);

VISITABLE_STRUCT(VkPhysicalDeviceFragmentDensityMapPropertiesEXT,sType,pNext,minFragmentDensityTexelSize,maxFragmentDensityTexelSize,fragmentDensityInvocations);

VISITABLE_STRUCT(VkRenderPassFragmentDensityMapCreateInfoEXT,sType,pNext,fragmentDensityMapAttachment);

VISITABLE_STRUCT(VkPhysicalDeviceScalarBlockLayoutFeaturesEXT,sType,pNext,scalarBlockLayout);

VISITABLE_STRUCT(VkPhysicalDeviceSubgroupSizeControlFeaturesEXT,sType,pNext,subgroupSizeControl,computeFullSubgroups);

VISITABLE_STRUCT(VkPhysicalDeviceSubgroupSizeControlPropertiesEXT,sType,pNext,minSubgroupSize,maxSubgroupSize,maxComputeWorkgroupSubgroups,requiredSubgroupSizeStages);

VISITABLE_STRUCT(VkPipelineShaderStageRequiredSubgroupSizeCreateInfoEXT,sType,pNext,requiredSubgroupSize);

VISITABLE_STRUCT(VkPhysicalDeviceShaderCoreProperties2AMD,sType,pNext,shaderCoreFeatures,activeComputeUnitCount);

VISITABLE_STRUCT(VkPhysicalDeviceCoherentMemoryFeaturesAMD,sType,pNext,deviceCoherentMemory);

VISITABLE_STRUCT(VkPhysicalDeviceMemoryBudgetPropertiesEXT,sType,pNext,heapBudget,heapUsage);

VISITABLE_STRUCT(VkPhysicalDeviceMemoryPriorityFeaturesEXT,sType,pNext,memoryPriority);

VISITABLE_STRUCT(VkMemoryPriorityAllocateInfoEXT,sType,pNext,priority);

VISITABLE_STRUCT(VkPhysicalDeviceDedicatedAllocationImageAliasingFeaturesNV,sType,pNext,dedicatedAllocationImageAliasing);

VISITABLE_STRUCT(VkPhysicalDeviceBufferDeviceAddressFeaturesEXT,sType,pNext,bufferDeviceAddress,bufferDeviceAddressCaptureReplay,bufferDeviceAddressMultiDevice);

VISITABLE_STRUCT(VkBufferDeviceAddressInfoEXT,sType,pNext,buffer);

VISITABLE_STRUCT(VkBufferDeviceAddressCreateInfoEXT,sType,pNext,deviceAddress);

VISITABLE_STRUCT(VkImageStencilUsageCreateInfoEXT,sType,pNext,stencilUsage);

VISITABLE_STRUCT(VkValidationFeaturesEXT,sType,pNext,enabledValidationFeatureCount,pEnabledValidationFeatures,disabledValidationFeatureCount,pDisabledValidationFeatures);

VISITABLE_STRUCT(VkCooperativeMatrixPropertiesNV,sType,pNext,MSize,NSize,KSize,AType,BType,CType,DType,scope);

VISITABLE_STRUCT(VkPhysicalDeviceCooperativeMatrixFeaturesNV,sType,pNext,cooperativeMatrix,cooperativeMatrixRobustBufferAccess);

VISITABLE_STRUCT(VkPhysicalDeviceCooperativeMatrixPropertiesNV,sType,pNext,cooperativeMatrixSupportedStages);

VISITABLE_STRUCT(VkPhysicalDeviceCoverageReductionModeFeaturesNV,sType,pNext,coverageReductionMode);

VISITABLE_STRUCT(VkPipelineCoverageReductionStateCreateInfoNV,sType,pNext,flags,coverageReductionMode);

VISITABLE_STRUCT(VkFramebufferMixedSamplesCombinationNV,sType,pNext,coverageReductionMode,rasterizationSamples,depthStencilSamples,colorSamples);

VISITABLE_STRUCT(VkPhysicalDeviceFragmentShaderInterlockFeaturesEXT,sType,pNext,fragmentShaderSampleInterlock,fragmentShaderPixelInterlock,fragmentShaderShadingRateInterlock);

VISITABLE_STRUCT(VkPhysicalDeviceYcbcrImageArraysFeaturesEXT,sType,pNext,ycbcrImageArrays);

VISITABLE_STRUCT(VkHeadlessSurfaceCreateInfoEXT,sType,pNext,flags);

VISITABLE_STRUCT(VkPhysicalDeviceLineRasterizationFeaturesEXT,sType,pNext,rectangularLines,bresenhamLines,smoothLines,stippledRectangularLines,stippledBresenhamLines,stippledSmoothLines);

VISITABLE_STRUCT(VkPhysicalDeviceLineRasterizationPropertiesEXT,sType,pNext,lineSubPixelPrecisionBits);

VISITABLE_STRUCT(VkPipelineRasterizationLineStateCreateInfoEXT,sType,pNext,lineRasterizationMode,stippledLineEnable,lineStippleFactor,lineStipplePattern);

VISITABLE_STRUCT(VkPhysicalDeviceHostQueryResetFeaturesEXT,sType,pNext,hostQueryReset);

VISITABLE_STRUCT(VkPhysicalDeviceIndexTypeUint8FeaturesEXT,sType,pNext,indexTypeUint8);

VISITABLE_STRUCT(VkPhysicalDeviceShaderDemoteToHelperInvocationFeaturesEXT,sType,pNext,shaderDemoteToHelperInvocation);

VISITABLE_STRUCT(VkPhysicalDeviceTexelBufferAlignmentFeaturesEXT,sType,pNext,texelBufferAlignment);

VISITABLE_STRUCT(VkPhysicalDeviceTexelBufferAlignmentPropertiesEXT,sType,pNext,storageTexelBufferOffsetAlignmentBytes,storageTexelBufferOffsetSingleTexelAlignment,uniformTexelBufferOffsetAlignmentBytes,uniformTexelBufferOffsetSingleTexelAlignment);

VISITABLE_STRUCT(VkXcbSurfaceCreateInfoKHR,sType,pNext,flags,connection,window);

#endif

