//AUTO-GENERATED File, caution before modifying

#ifndef VULKANENUMMAP_HPP
 #define VULKANENUMMAP_HPP

#include "VulkanConfigurator.hpp"

namespace configuration
{

constexpr Configurator::EnumMapInitializer::EnumMapInitializer() noexcept
{

enumMap.add("VK_STRUCTURE_TYPE_MEMORY_ALLOCATE_INFO",5);
enumMap.add("VK_STRUCTURE_TYPE_MAPPED_MEMORY_RANGE",6);
enumMap.add("VK_STRUCTURE_TYPE_COMMAND_BUFFER_ALLOCATE_INFO",40);
enumMap.add("VK_COMMAND_BUFFER_LEVEL_PRIMARY",0);
enumMap.add("VK_STRUCTURE_TYPE_COMMAND_BUFFER_BEGIN_INFO",42);
enumMap.add("VK_STRUCTURE_TYPE_COMMAND_BUFFER_INHERITANCE_INFO",41);
enumMap.add("VK_STRUCTURE_TYPE_COMMAND_POOL_CREATE_INFO",39);
enumMap.add("VK_COMMAND_POOL_CREATE_RESET_COMMAND_BUFFER_BIT",2);
enumMap.add("VK_STRUCTURE_TYPE_RENDER_PASS_BEGIN_INFO",43);
enumMap.add("VK_STRUCTURE_TYPE_RENDER_PASS_CREATE_INFO",38);
enumMap.add("VK_PIPELINE_BIND_POINT_GRAPHICS",0);
enumMap.add("VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT",8192);
enumMap.add("VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT",1024);
enumMap.add("VK_ACCESS_MEMORY_READ_BIT",32768);
enumMap.add("VK_ACCESS_COLOR_ATTACHMENT_READ_BIT",128);
enumMap.add("VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT",256);
enumMap.add("VK_DEPENDENCY_BY_REGION_BIT",1);
enumMap.add("VK_STRUCTURE_TYPE_IMAGE_MEMORY_BARRIER",45);
enumMap.add("VK_STRUCTURE_TYPE_BUFFER_MEMORY_BARRIER",44);
enumMap.add("VK_STRUCTURE_TYPE_MEMORY_BARRIER",46);
enumMap.add("VK_IMAGE_VIEW_TYPE_2D",1);
enumMap.add("VK_STRUCTURE_TYPE_IMAGE_CREATE_INFO",14);
enumMap.add("VK_SAMPLE_COUNT_1_BIT",1);
enumMap.add("VK_IMAGE_TILING_OPTIMAL",0);
enumMap.add("VK_IMAGE_USAGE_TRANSFER_SRC_BIT",1);
enumMap.add("VK_IMAGE_USAGE_DEPTH_STENCIL_ATTACHMENT_BIT",32);
enumMap.add("VK_STRUCTURE_TYPE_SAMPLER_CREATE_INFO",31);
enumMap.add("VK_STRUCTURE_TYPE_IMAGE_VIEW_CREATE_INFO",15);
enumMap.add("VK_IMAGE_ASPECT_COLOR_BIT",1);
enumMap.add("VK_STRUCTURE_TYPE_SUBMIT_INFO",4);
enumMap.add("VK_STRUCTURE_TYPE_FRAMEBUFFER_CREATE_INFO",37);
enumMap.add("VK_STRUCTURE_TYPE_BUFFER_CREATE_INFO",12);
enumMap.add("VK_STRUCTURE_TYPE_FENCE_CREATE_INFO",8);
enumMap.add("VK_FENCE_CREATE_SIGNALED_BIT",1);
enumMap.add("VK_STRUCTURE_TYPE_EVENT_CREATE_INFO",10);
enumMap.add("VK_STRUCTURE_TYPE_DESCRIPTOR_SET_LAYOUT_CREATE_INFO",32);
enumMap.add("VK_STRUCTURE_TYPE_DESCRIPTOR_SET_ALLOCATE_INFO",34);
enumMap.add("VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET",35);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO",30);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_VERTEX_INPUT_STATE_CREATE_INFO",19);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_INPUT_ASSEMBLY_STATE_CREATE_INFO",20);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_RASTERIZATION_STATE_CREATE_INFO",23);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_COLOR_BLEND_STATE_CREATE_INFO",26);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_DEPTH_STENCIL_STATE_CREATE_INFO",25);
enumMap.add("VK_COMPARE_OP_ALWAYS",7);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_VIEWPORT_STATE_CREATE_INFO",22);
enumMap.add("VK_STRUCTURE_TYPE_PIPELINE_CACHE_CREATE_INFO",17);
enumMap.add("VK_STRUCTURE_TYPE_APPLICATION_INFO",0);
enumMap.add("VK_STRUCTURE_TYPE_INSTANCE_CREATE_INFO",1);
enumMap.add("VK_STRUCTURE_TYPE_XCB_SURFACE_CREATE_INFO_KHR",1000005000);
enumMap.add("VK_STRUCTURE_TYPE_SWAPCHAIN_CREATE_INFO_KHR",1000001000);
enumMap.add("VK_IMAGE_USAGE_COLOR_ATTACHMENT_BIT",16);
enumMap.add("VK_SHARING_MODE_EXCLUSIVE",0);
enumMap.add("VK_COMPONENT_SWIZZLE_R",3);
enumMap.add("VK_COMPONENT_SWIZZLE_G",4);
enumMap.add("VK_COMPONENT_SWIZZLE_B",5);
enumMap.add("VK_COMPONENT_SWIZZLE_A",6);
enumMap.add("VK_ATTACHMENT_LOAD_OP_CLEAR",1);
enumMap.add("VK_ATTACHMENT_STORE_OP_STORE",0);
enumMap.add("VK_ATTACHMENT_LOAD_OP_DONT_CARE",2);
enumMap.add("VK_ATTACHMENT_STORE_OP_DONT_CARE",1);
enumMap.add("VK_IMAGE_LAYOUT_UNDEFINED",0);
enumMap.add("VK_IMAGE_LAYOUT_PRESENT_SRC_KHR",1000001002);
enumMap.add("VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL",3);
enumMap.add("VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL",2);
}
}
#endif
